/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author stevenblaivas
 */
import java.awt.Color;
public class Keyboard extends javax.swing.JFrame {

    private int KeyPressed;

    /**
     * Creates new form Keyboard
     */
    public Keyboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton20 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonTildekey = new javax.swing.JButton();
        jButtonTabskey = new javax.swing.JButton();
        jButtonCaps = new javax.swing.JButton();
        jButtonShift = new javax.swing.JButton();
        jButton1key = new javax.swing.JButton();
        jButton3key = new javax.swing.JButton();
        jButton4key = new javax.swing.JButton();
        jButton5key = new javax.swing.JButton();
        jButton6key = new javax.swing.JButton();
        jButton8Key = new javax.swing.JButton();
        jButton7key = new javax.swing.JButton();
        jButton9key = new javax.swing.JButton();
        jButtonMinuskey = new javax.swing.JButton();
        jButton0key = new javax.swing.JButton();
        jButtonBSKey = new javax.swing.JButton();
        jButtonEqualskey = new javax.swing.JButton();
        jButtonQkey = new javax.swing.JButton();
        jButtonWkey = new javax.swing.JButton();
        jButtonEkey = new javax.swing.JButton();
        jButtonRkey = new javax.swing.JButton();
        jButtonTkey = new javax.swing.JButton();
        jButtonYkey = new javax.swing.JButton();
        jButtonUkey = new javax.swing.JButton();
        jButtonIkey = new javax.swing.JButton();
        jButtonOkey = new javax.swing.JButton();
        jButtonPkey = new javax.swing.JButton();
        jButtonLeftBkey = new javax.swing.JButton();
        jButtonRightBkey = new javax.swing.JButton();
        jButtonSlashkey = new javax.swing.JButton();
        jButtonAkey = new javax.swing.JButton();
        jButtonHkey = new javax.swing.JButton();
        jButtonGkey = new javax.swing.JButton();
        jButtonSkey = new javax.swing.JButton();
        jButtonDkey = new javax.swing.JButton();
        jButtonFkey = new javax.swing.JButton();
        jButtonEnterkey = new javax.swing.JButton();
        jButtonQuoteskey = new javax.swing.JButton();
        jButtonColonkey = new javax.swing.JButton();
        jButtonLkey = new javax.swing.JButton();
        jButtonKkey = new javax.swing.JButton();
        jButtonJkey = new javax.swing.JButton();
        jButtonXkey = new javax.swing.JButton();
        jButtonZkey = new javax.swing.JButton();
        jButtonBkey = new javax.swing.JButton();
        jButtonCkey = new javax.swing.JButton();
        jButtonVkey = new javax.swing.JButton();
        jButtonMkey = new javax.swing.JButton();
        jButtonNkey = new javax.swing.JButton();
        jButtonPeriodkey = new javax.swing.JButton();
        jButtonCommakey = new javax.swing.JButton();
        jButtonQuestionkey = new javax.swing.JButton();
        jButtonUpkey = new javax.swing.JButton();
        jButtonRightkey = new javax.swing.JButton();
        jButtonDownkey = new javax.swing.JButton();
        jButtonLeftkey = new javax.swing.JButton();
        jButtonSpaceKey = new javax.swing.JButton();
        jButton2key1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton20.setText("jButton20");

        jButton8.setText("jButton8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jButtonTildekey.setText("~");

        jButtonTabskey.setText("Tabs");

        jButtonCaps.setText("Caps");
        jButtonCaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCapsActionPerformed(evt);
            }
        });

        jButtonShift.setText("Shift");
        jButtonShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShiftActionPerformed(evt);
            }
        });

        jButton1key.setText("1");
        jButton1key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1keyActionPerformed(evt);
            }
        });
        jButton1key.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton1keyKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1keyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1keyKeyReleased(evt);
            }
        });

        jButton3key.setText("3");

        jButton4key.setText("4");
        jButton4key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4keyActionPerformed(evt);
            }
        });

        jButton5key.setText("5");
        jButton5key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5keyActionPerformed(evt);
            }
        });

        jButton6key.setText("6");

        jButton8Key.setText("8");

        jButton7key.setText("7");
        jButton7key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7keyActionPerformed(evt);
            }
        });

        jButton9key.setText("9");
        jButton9key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9keyActionPerformed(evt);
            }
        });

        jButtonMinuskey.setText("-");

        jButton0key.setText("0");
        jButton0key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0keyActionPerformed(evt);
            }
        });

        jButtonBSKey.setText("Backspace");
        jButtonBSKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBSKeyActionPerformed(evt);
            }
        });

        jButtonEqualskey.setText("=");
        jButtonEqualskey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualskeyActionPerformed(evt);
            }
        });

        jButtonQkey.setText("Q");
        jButtonQkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQkeyActionPerformed(evt);
            }
        });

        jButtonWkey.setText("W");
        jButtonWkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWkeyActionPerformed(evt);
            }
        });

        jButtonEkey.setText("E");
        jButtonEkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEkeyActionPerformed(evt);
            }
        });

        jButtonRkey.setText("R");
        jButtonRkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRkeyActionPerformed(evt);
            }
        });

        jButtonTkey.setText("T");
        jButtonTkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTkeyActionPerformed(evt);
            }
        });

        jButtonYkey.setText("Y");
        jButtonYkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYkeyActionPerformed(evt);
            }
        });

        jButtonUkey.setText("U");
        jButtonUkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUkeyActionPerformed(evt);
            }
        });

        jButtonIkey.setText("I");
        jButtonIkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIkeyActionPerformed(evt);
            }
        });

        jButtonOkey.setText("O");
        jButtonOkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkeyActionPerformed(evt);
            }
        });

        jButtonPkey.setText("P");
        jButtonPkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPkeyActionPerformed(evt);
            }
        });

        jButtonLeftBkey.setText("[");
        jButtonLeftBkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeftBkeyActionPerformed(evt);
            }
        });

        jButtonRightBkey.setText("]");
        jButtonRightBkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRightBkeyActionPerformed(evt);
            }
        });

        jButtonSlashkey.setText("\\");
            jButtonSlashkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonSlashkeyActionPerformed(evt);
                }
            });

            jButtonAkey.setText("A");
            jButtonAkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonAkeyActionPerformed(evt);
                }
            });

            jButtonHkey.setText("H");
            jButtonHkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonHkeyActionPerformed(evt);
                }
            });

            jButtonGkey.setText("G");
            jButtonGkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonGkeyActionPerformed(evt);
                }
            });

            jButtonSkey.setText("S");
            jButtonSkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonSkeyActionPerformed(evt);
                }
            });

            jButtonDkey.setText("D");
            jButtonDkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonDkeyActionPerformed(evt);
                }
            });

            jButtonFkey.setText("F");
            jButtonFkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonFkeyActionPerformed(evt);
                }
            });

            jButtonEnterkey.setText("Enter");
            jButtonEnterkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonEnterkeyActionPerformed(evt);
                }
            });

            jButtonQuoteskey.setText("\"");
            jButtonQuoteskey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonQuoteskeyActionPerformed(evt);
                }
            });

            jButtonColonkey.setText(":");
            jButtonColonkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonColonkeyActionPerformed(evt);
                }
            });

            jButtonLkey.setText("L");
            jButtonLkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonLkeyActionPerformed(evt);
                }
            });

            jButtonKkey.setText("K");
            jButtonKkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonKkeyActionPerformed(evt);
                }
            });

            jButtonJkey.setText("J");
            jButtonJkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonJkeyActionPerformed(evt);
                }
            });

            jButtonXkey.setText("X");
            jButtonXkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonXkeyActionPerformed(evt);
                }
            });

            jButtonZkey.setText("Z");
            jButtonZkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonZkeyActionPerformed(evt);
                }
            });

            jButtonBkey.setText("B");
            jButtonBkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonBkeyActionPerformed(evt);
                }
            });

            jButtonCkey.setText("C");
            jButtonCkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonCkeyActionPerformed(evt);
                }
            });

            jButtonVkey.setText("V");
            jButtonVkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonVkeyActionPerformed(evt);
                }
            });

            jButtonMkey.setText("M");
            jButtonMkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonMkeyActionPerformed(evt);
                }
            });

            jButtonNkey.setText("N");
            jButtonNkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonNkeyActionPerformed(evt);
                }
            });

            jButtonPeriodkey.setText(".");
            jButtonPeriodkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonPeriodkeyActionPerformed(evt);
                }
            });

            jButtonCommakey.setText(",");
            jButtonCommakey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonCommakeyActionPerformed(evt);
                }
            });

            jButtonQuestionkey.setText("?");
            jButtonQuestionkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonQuestionkeyActionPerformed(evt);
                }
            });

            jButtonUpkey.setText("^");
            jButtonUpkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonUpkeyActionPerformed(evt);
                }
            });

            jButtonRightkey.setText(">");
            jButtonRightkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonRightkeyActionPerformed(evt);
                }
            });

            jButtonDownkey.setText("↓");
            jButtonDownkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonDownkeyActionPerformed(evt);
                }
            });

            jButtonLeftkey.setText("<");
            jButtonLeftkey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonLeftkeyActionPerformed(evt);
                }
            });

            jButtonSpaceKey.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonSpaceKeyActionPerformed(evt);
                }
            });

            jButton2key1.setText("2");
            jButton2key1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2key1ActionPerformed(evt);
                }
            });

            jLabel1.setText("Type some text using your keyboard. The keys you press will be highlighted and the text will be displayed.");

            jLabel2.setText("Note: Clicking the buttons with your mouse will not perform any action.");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonTildekey, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1key, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2key1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3key, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton4key, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton5key, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton6key, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton7key, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton8Key, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton9key, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton0key, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonMinuskey, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonEqualskey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonBSKey)
                                    .addGap(0, 24, Short.MAX_VALUE)))
                            .addGap(18, 18, 18))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButtonTabskey, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonQkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonWkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonEkey, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonRkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonTkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonYkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonUkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonIkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonOkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonPkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonLeftBkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButtonCaps, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonAkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonSkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonDkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonFkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonGkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonHkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonJkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonKkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonLkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonColonkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonQuoteskey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButtonShift)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonZkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonXkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jButtonCkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButtonVkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButtonBkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButtonNkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButtonMkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButtonCommakey, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jButtonSpaceKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonPeriodkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonQuestionkey, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButtonLeftkey, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonDownkey, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonRightkey, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButtonRightBkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonSlashkey, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonUpkey, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonEnterkey, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            );

            jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCaps, jButtonTabskey});

            jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton0key, jButton1key, jButton2key1, jButton3key, jButton4key, jButton5key, jButton6key, jButton7key, jButton8Key, jButton9key, jButtonAkey, jButtonBkey, jButtonCkey, jButtonColonkey, jButtonCommakey, jButtonDkey, jButtonDownkey, jButtonEkey, jButtonEqualskey, jButtonFkey, jButtonGkey, jButtonHkey, jButtonIkey, jButtonJkey, jButtonKkey, jButtonLeftBkey, jButtonLeftkey, jButtonLkey, jButtonMinuskey, jButtonMkey, jButtonNkey, jButtonOkey, jButtonPeriodkey, jButtonPkey, jButtonQkey, jButtonQuestionkey, jButtonQuoteskey, jButtonRightBkey, jButtonRightkey, jButtonRkey, jButtonSkey, jButtonSlashkey, jButtonTildekey, jButtonTkey, jButtonUkey, jButtonUpkey, jButtonVkey, jButtonWkey, jButtonXkey, jButtonYkey, jButtonZkey});

            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addGap(5, 5, 5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonTildekey)
                        .addComponent(jButton3key)
                        .addComponent(jButton4key)
                        .addComponent(jButton1key)
                        .addComponent(jButton5key)
                        .addComponent(jButton6key)
                        .addComponent(jButton7key)
                        .addComponent(jButton8Key)
                        .addComponent(jButton0key)
                        .addComponent(jButtonMinuskey)
                        .addComponent(jButtonEqualskey)
                        .addComponent(jButtonBSKey)
                        .addComponent(jButton9key)
                        .addComponent(jButton2key1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonTabskey)
                        .addComponent(jButtonQkey)
                        .addComponent(jButtonWkey)
                        .addComponent(jButtonEkey)
                        .addComponent(jButtonRkey)
                        .addComponent(jButtonTkey)
                        .addComponent(jButtonYkey)
                        .addComponent(jButtonUkey)
                        .addComponent(jButtonIkey)
                        .addComponent(jButtonOkey)
                        .addComponent(jButtonPkey)
                        .addComponent(jButtonLeftBkey)
                        .addComponent(jButtonRightBkey)
                        .addComponent(jButtonSlashkey))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonCaps, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAkey)
                            .addComponent(jButtonSkey)
                            .addComponent(jButtonDkey)
                            .addComponent(jButtonFkey)
                            .addComponent(jButtonGkey)
                            .addComponent(jButtonHkey)
                            .addComponent(jButtonJkey)
                            .addComponent(jButtonKkey)
                            .addComponent(jButtonLkey)
                            .addComponent(jButtonColonkey)
                            .addComponent(jButtonQuoteskey)
                            .addComponent(jButtonEnterkey)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonUpkey, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonShift)
                            .addComponent(jButtonZkey)
                            .addComponent(jButtonXkey)
                            .addComponent(jButtonCkey)
                            .addComponent(jButtonVkey)
                            .addComponent(jButtonBkey)
                            .addComponent(jButtonNkey)
                            .addComponent(jButtonMkey)
                            .addComponent(jButtonCommakey)
                            .addComponent(jButtonPeriodkey)
                            .addComponent(jButtonQuestionkey)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonRightkey)
                        .addComponent(jButtonSpaceKey, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonLeftkey)
                        .addComponent(jButtonDownkey))
                    .addContainerGap(21, Short.MAX_VALUE))
            );

            jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton0key, jButton1key, jButton2key1, jButton3key, jButton4key, jButton5key, jButton6key, jButton7key, jButton8Key, jButton9key, jButtonAkey, jButtonBSKey, jButtonBkey, jButtonCaps, jButtonCkey, jButtonColonkey, jButtonCommakey, jButtonDkey, jButtonEkey, jButtonEnterkey, jButtonEqualskey, jButtonFkey, jButtonGkey, jButtonHkey, jButtonIkey, jButtonJkey, jButtonKkey, jButtonLeftBkey, jButtonLkey, jButtonMinuskey, jButtonMkey, jButtonNkey, jButtonOkey, jButtonPeriodkey, jButtonPkey, jButtonQkey, jButtonQuestionkey, jButtonQuoteskey, jButtonRightBkey, jButtonRkey, jButtonShift, jButtonSkey, jButtonSlashkey, jButtonTabskey, jButtonTildekey, jButtonTkey, jButtonUkey, jButtonVkey, jButtonWkey, jButtonXkey, jButtonYkey, jButtonZkey});

            jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonDownkey, jButtonLeftkey, jButtonRightkey, jButtonSpaceKey, jButtonUpkey});

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButtonCapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCapsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCapsActionPerformed

    private void jButton1keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1keyActionPerformed

    private void jButton4keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4keyActionPerformed

    private void jButtonEqualskeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualskeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEqualskeyActionPerformed

    private void jButtonBSKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBSKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBSKeyActionPerformed

    private void jButton9keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9keyActionPerformed

    private void jButton5keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5keyActionPerformed

    private void jButton7keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7keyActionPerformed

    private void jButton0keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton0keyActionPerformed

    private void jButtonShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShiftActionPerformed

    private void jButtonQkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQkeyActionPerformed

    private void jButtonWkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWkeyActionPerformed

    private void jButtonEkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEkeyActionPerformed

    private void jButtonRkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRkeyActionPerformed

    private void jButtonTkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTkeyActionPerformed

    private void jButtonYkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonYkeyActionPerformed

    private void jButtonUkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUkeyActionPerformed

    private void jButtonIkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIkeyActionPerformed

    private void jButtonOkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOkeyActionPerformed

    private void jButtonPkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPkeyActionPerformed

    private void jButtonLeftBkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeftBkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLeftBkeyActionPerformed

    private void jButtonRightBkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRightBkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRightBkeyActionPerformed

    private void jButtonSlashkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSlashkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSlashkeyActionPerformed

    private void jButtonAkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAkeyActionPerformed

    private void jButtonHkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHkeyActionPerformed

    private void jButtonGkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGkeyActionPerformed

    private void jButtonSkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSkeyActionPerformed

    private void jButtonDkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDkeyActionPerformed

    private void jButtonFkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFkeyActionPerformed

    private void jButtonEnterkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEnterkeyActionPerformed

    private void jButtonQuoteskeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuoteskeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuoteskeyActionPerformed

    private void jButtonColonkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColonkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonColonkeyActionPerformed

    private void jButtonLkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLkeyActionPerformed

    private void jButtonKkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKkeyActionPerformed

    private void jButtonJkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJkeyActionPerformed

    private void jButtonXkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXkeyActionPerformed

    private void jButtonZkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonZkeyActionPerformed

    private void jButtonBkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBkeyActionPerformed

    private void jButtonCkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCkeyActionPerformed

    private void jButtonVkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVkeyActionPerformed

    private void jButtonMkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMkeyActionPerformed

    private void jButtonNkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNkeyActionPerformed

    private void jButtonPeriodkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeriodkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPeriodkeyActionPerformed

    private void jButtonCommakeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCommakeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCommakeyActionPerformed

    private void jButtonQuestionkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuestionkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuestionkeyActionPerformed

    private void jButtonUpkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpkeyActionPerformed

    private void jButtonRightkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRightkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRightkeyActionPerformed

    private void jButtonDownkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDownkeyActionPerformed

    private void jButtonLeftkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeftkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLeftkeyActionPerformed

    private void jButtonSpaceKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpaceKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSpaceKeyActionPerformed

    private void jButton2key1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2key1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2key1ActionPerformed

    private void jButton1keyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1keyKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1keyKeyPressed

    private void jButton1keyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1keyKeyReleased
        // TODO add your handling code here:
         //Color Yellow = new Color(255,255,0);

    }//GEN-LAST:event_jButton1keyKeyReleased

    private void jButton1keyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1keyKeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton1keyKeyTyped

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
        Color Yellow = new Color(255,255,0);//Yellow color
        //Oter keys
        if(evt.getKeyCode()==192){
            jButtonTildekey.setBackground(Yellow); 
         }
        if(evt.getKeyCode()==45){
            jButtonMinuskey.setBackground(Yellow); 
        }
        if(evt.getKeyCode()==61){
            jButtonEqualskey.setBackground(Yellow); 
        }
        if(evt.getKeyCode()==8){
            jButtonBSKey.setBackground(Yellow); 
        }
        if(evt.getKeyCode()==9){
           jButtonTabskey.setBackground(Yellow); 
        }       
        if(evt.getKeyCode()==91){
            jButtonLeftBkey.setBackground(Yellow); 
        }       
        if(evt.getKeyCode()==93){
             jButtonRightBkey.setBackground(Yellow); 
            }       
        if(evt.getKeyCode()==92){
            jButtonSlashkey.setBackground(Yellow);  
        }
        if(evt.getKeyCode()==20){
             jButtonCaps.setBackground(Yellow);          
        }
        if(evt.getKeyCode()==59){
             jButtonColonkey.setBackground(Yellow);          
        }
         if(evt.getKeyCode()==222){
             jButtonQuoteskey.setBackground(Yellow);   
          
        }
        if(evt.getKeyCode()==10){
             jButtonEnterkey.setBackground(Yellow);  
        }
        
        if(evt.getKeyCode()==16){
             jButtonShift.setBackground(Yellow);   
          
        }
        if(evt.getKeyCode()==44){
             jButtonCommakey.setBackground(Yellow);  
        }
        if(evt.getKeyCode()==46){
             jButtonPeriodkey.setBackground(Yellow);  
        }
        if(evt.getKeyCode()==47){
             jButtonQuestionkey.setBackground(Yellow);  
        }
        if(evt.getKeyCode()==32){
             jButtonSpaceKey.setBackground(Yellow);  
        }
        if(evt.getKeyCode()==37){
            jButtonLeftkey.setBackground(Yellow);  
        }
        if(evt.getKeyCode()==38){
             jButtonUpkey.setBackground(Yellow);  
        }
        if(evt.getKeyCode()==39){
             jButtonRightkey.setBackground(Yellow);  
        }
        if(evt.getKeyCode()==40){
             jButtonDownkey.setBackground(Yellow);  
        }
        
        
        //Number Keys
        if(evt.getKeyCode() == 49){
                jButton1key.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 50){
                jButton2key1.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 51){
                jButton3key.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 52){
                jButton4key.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 53){
                jButton5key.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 54){
                jButton6key.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 55){
                jButton7key.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 56){
                jButton8Key.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 57){
                jButton9key.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 48){
                jButton0key.setBackground(Yellow);          
        }
        
        
        //Letters
        if(evt.getKeyCode() == 65){
            jButtonAkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 66){
                jButtonBkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 67){
                jButtonCkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 68){
                jButtonDkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 69){
                jButtonEkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 70){
                jButtonFkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 71){
                jButtonGkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 72){
                jButtonHkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 73){
                jButtonIkey.setBackground(Yellow);          
        }
                  
        
          if(evt.getKeyCode() == 74){
                jButtonJkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 75){
                jButtonKkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 76){
                jButtonLkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 77){
                jButtonMkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 78){
                jButtonNkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 79){
                jButtonOkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 80){
                jButtonPkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 81){
                jButtonQkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 82){
                jButtonRkey.setBackground(Yellow);          
          
        }
        if(evt.getKeyCode() == 83){
                jButtonSkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 84){
                jButtonTkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 85){
                jButtonUkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 86){
                jButtonVkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 87){
                jButtonWkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 88){
                jButtonXkey.setBackground(Yellow);     
        }
        if(evt.getKeyCode() == 89){
                jButtonYkey.setBackground(Yellow);          
        }
        if(evt.getKeyCode() == 90){
                jButtonZkey.setBackground(Yellow);   
        }
       
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
        // TODO add your handling code here:
        Color Default = new Color(187,187,187);//Default key color
        //Other keys
        if(evt.getKeyCode()==192){
             jButtonTildekey.setBackground(Default); 
        }       
        if(evt.getKeyCode()==45){
            jButtonMinuskey.setBackground(Default); 
        }       
        if(evt.getKeyCode()==61){
             jButtonEqualskey.setBackground(Default); 
            }       
        if(evt.getKeyCode()==8){
             jButtonBSKey.setBackground(Default);          
        }
        if(evt.getKeyCode()==9){
            jButtonTabskey.setBackground(Default); 
        }       
        if(evt.getKeyCode()==91){
            jButtonLeftBkey.setBackground(Default); 
        }       
        if(evt.getKeyCode()==93){
             jButtonRightBkey.setBackground(Default); 
            }       
        if(evt.getKeyCode()==92){
             jButtonSlashkey.setBackground(Default);          
        }
        
        if(evt.getKeyCode()==20){
             jButtonCaps.setBackground(Default);          
        }
        if(evt.getKeyCode()==59){
             jButtonColonkey.setBackground(Default);          
        }
         if(evt.getKeyCode()==222){
             jButtonQuoteskey.setBackground(Default);   
          
        }
        if(evt.getKeyCode()==10){
             jButtonEnterkey.setBackground(Default);          
        }
        if(evt.getKeyCode()==16){
            jButtonShift.setBackground(Default);   
          
        }
        if(evt.getKeyCode()==44){
             jButtonCommakey.setBackground(Default);  
        }
        if(evt.getKeyCode()==46){
             jButtonPeriodkey.setBackground(Default);  
        }
        if(evt.getKeyCode()==47){
             jButtonQuestionkey.setBackground(Default);  
        }
        if(evt.getKeyCode()==32){
             jButtonSpaceKey.setBackground(Default);  
        }
        if(evt.getKeyCode()==37){
            jButtonLeftkey.setBackground(Default);  
        }
        if(evt.getKeyCode()==38){
             jButtonUpkey.setBackground(Default);  
        }
        if(evt.getKeyCode()==39){
             jButtonRightkey.setBackground(Default);  
        }
        if(evt.getKeyCode()==40){
             jButtonDownkey.setBackground(Default);  
        }
        
        //Number Keys
        if(evt.getKeyCode()==49){
                jButton1key.setBackground(Default);        
        }
          if(evt.getKeyCode() == 50){
                jButton2key1.setBackground(Default);          
        }
        if(evt.getKeyCode() == 51){
                jButton3key.setBackground(Default);          
        }
        if(evt.getKeyCode() == 52){
                jButton4key.setBackground(Default);          
        }
        if(evt.getKeyCode() == 53){
                jButton5key.setBackground(Default);          
        }
        if(evt.getKeyCode() == 54){
                jButton6key.setBackground(Default);          
        }
        if(evt.getKeyCode() == 55){
                jButton7key.setBackground(Default);          
        }
        if(evt.getKeyCode() == 56){
                jButton8Key.setBackground(Default);          
        }
        if(evt.getKeyCode() == 57){
                jButton9key.setBackground(Default);          
        }
        if(evt.getKeyCode() == 48){
                jButton0key.setBackground(Default);          
        }
                       
       //Letters 
       if(evt.getKeyCode() == 65){
            jButtonAkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 66){
                jButtonBkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 67){
                jButtonCkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 68){
                jButtonDkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 69){
                jButtonEkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 70){
                jButtonFkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 71){
                jButtonGkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 72){
                jButtonHkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 73){
                jButtonIkey.setBackground(Default);          
        }
                  
        
          if(evt.getKeyCode() == 74){
                jButtonJkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 75){
                jButtonKkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 76){
                jButtonLkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 77){
                jButtonMkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 78){
                jButtonNkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 79){
                jButtonOkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 80){
                jButtonPkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 81){
                jButtonQkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 82){
                jButtonRkey.setBackground(Default);          
          
        }
        if(evt.getKeyCode() == 83){
                jButtonSkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 84){
                jButtonTkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 85){
                jButtonUkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 86){
                jButtonVkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 87){
                jButtonWkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 88){
                jButtonXkey.setBackground(Default);     
        }
        if(evt.getKeyCode() == 89){
                jButtonYkey.setBackground(Default);          
        }
        if(evt.getKeyCode() == 90){
                jButtonZkey.setBackground(Default);   
        }
    

    }//GEN-LAST:event_jTextArea1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Keyboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Keyboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Keyboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Keyboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Keyboard().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0key;
    private javax.swing.JButton jButton1key;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton2key1;
    private javax.swing.JButton jButton3key;
    private javax.swing.JButton jButton4key;
    private javax.swing.JButton jButton5key;
    private javax.swing.JButton jButton6key;
    private javax.swing.JButton jButton7key;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton8Key;
    private javax.swing.JButton jButton9key;
    private javax.swing.JButton jButtonAkey;
    private javax.swing.JButton jButtonBSKey;
    private javax.swing.JButton jButtonBkey;
    private javax.swing.JButton jButtonCaps;
    private javax.swing.JButton jButtonCkey;
    private javax.swing.JButton jButtonColonkey;
    private javax.swing.JButton jButtonCommakey;
    private javax.swing.JButton jButtonDkey;
    private javax.swing.JButton jButtonDownkey;
    private javax.swing.JButton jButtonEkey;
    private javax.swing.JButton jButtonEnterkey;
    private javax.swing.JButton jButtonEqualskey;
    private javax.swing.JButton jButtonFkey;
    private javax.swing.JButton jButtonGkey;
    private javax.swing.JButton jButtonHkey;
    private javax.swing.JButton jButtonIkey;
    private javax.swing.JButton jButtonJkey;
    private javax.swing.JButton jButtonKkey;
    private javax.swing.JButton jButtonLeftBkey;
    private javax.swing.JButton jButtonLeftkey;
    private javax.swing.JButton jButtonLkey;
    private javax.swing.JButton jButtonMinuskey;
    private javax.swing.JButton jButtonMkey;
    private javax.swing.JButton jButtonNkey;
    private javax.swing.JButton jButtonOkey;
    private javax.swing.JButton jButtonPeriodkey;
    private javax.swing.JButton jButtonPkey;
    private javax.swing.JButton jButtonQkey;
    private javax.swing.JButton jButtonQuestionkey;
    private javax.swing.JButton jButtonQuoteskey;
    private javax.swing.JButton jButtonRightBkey;
    private javax.swing.JButton jButtonRightkey;
    private javax.swing.JButton jButtonRkey;
    private javax.swing.JButton jButtonShift;
    private javax.swing.JButton jButtonSkey;
    private javax.swing.JButton jButtonSlashkey;
    private javax.swing.JButton jButtonSpaceKey;
    private javax.swing.JButton jButtonTabskey;
    private javax.swing.JButton jButtonTildekey;
    private javax.swing.JButton jButtonTkey;
    private javax.swing.JButton jButtonUkey;
    private javax.swing.JButton jButtonUpkey;
    private javax.swing.JButton jButtonVkey;
    private javax.swing.JButton jButtonWkey;
    private javax.swing.JButton jButtonXkey;
    private javax.swing.JButton jButtonYkey;
    private javax.swing.JButton jButtonZkey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
